// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: objects.proto

package proto;

public final class DataFormats {
  private DataFormats() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SerializedDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:formats.SerializedData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .formats.Data data = 1;</code>
     */
    java.util.List<proto.DataFormats.Data> 
        getDataList();
    /**
     * <code>repeated .formats.Data data = 1;</code>
     */
    proto.DataFormats.Data getData(int index);
    /**
     * <code>repeated .formats.Data data = 1;</code>
     */
    int getDataCount();
    /**
     * <code>repeated .formats.Data data = 1;</code>
     */
    java.util.List<? extends proto.DataFormats.DataOrBuilder> 
        getDataOrBuilderList();
    /**
     * <code>repeated .formats.Data data = 1;</code>
     */
    proto.DataFormats.DataOrBuilder getDataOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code formats.SerializedData}
   */
  public  static final class SerializedData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:formats.SerializedData)
      SerializedDataOrBuilder {
    // Use SerializedData.newBuilder() to construct.
    private SerializedData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SerializedData() {
      data_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SerializedData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                data_ = new java.util.ArrayList<proto.DataFormats.Data>();
                mutable_bitField0_ |= 0x00000001;
              }
              data_.add(
                  input.readMessage(proto.DataFormats.Data.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          data_ = java.util.Collections.unmodifiableList(data_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.DataFormats.internal_static_formats_SerializedData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.DataFormats.internal_static_formats_SerializedData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.DataFormats.SerializedData.class, proto.DataFormats.SerializedData.Builder.class);
    }

    public static final int DATA_FIELD_NUMBER = 1;
    private java.util.List<proto.DataFormats.Data> data_;
    /**
     * <code>repeated .formats.Data data = 1;</code>
     */
    public java.util.List<proto.DataFormats.Data> getDataList() {
      return data_;
    }
    /**
     * <code>repeated .formats.Data data = 1;</code>
     */
    public java.util.List<? extends proto.DataFormats.DataOrBuilder> 
        getDataOrBuilderList() {
      return data_;
    }
    /**
     * <code>repeated .formats.Data data = 1;</code>
     */
    public int getDataCount() {
      return data_.size();
    }
    /**
     * <code>repeated .formats.Data data = 1;</code>
     */
    public proto.DataFormats.Data getData(int index) {
      return data_.get(index);
    }
    /**
     * <code>repeated .formats.Data data = 1;</code>
     */
    public proto.DataFormats.DataOrBuilder getDataOrBuilder(
        int index) {
      return data_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < data_.size(); i++) {
        output.writeMessage(1, data_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < data_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, data_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.DataFormats.SerializedData)) {
        return super.equals(obj);
      }
      proto.DataFormats.SerializedData other = (proto.DataFormats.SerializedData) obj;

      boolean result = true;
      result = result && getDataList()
          .equals(other.getDataList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getDataCount() > 0) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getDataList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.DataFormats.SerializedData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.DataFormats.SerializedData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.DataFormats.SerializedData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.DataFormats.SerializedData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.DataFormats.SerializedData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.DataFormats.SerializedData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.DataFormats.SerializedData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.DataFormats.SerializedData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.DataFormats.SerializedData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.DataFormats.SerializedData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.DataFormats.SerializedData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code formats.SerializedData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:formats.SerializedData)
        proto.DataFormats.SerializedDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.DataFormats.internal_static_formats_SerializedData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.DataFormats.internal_static_formats_SerializedData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.DataFormats.SerializedData.class, proto.DataFormats.SerializedData.Builder.class);
      }

      // Construct using proto.DataFormats.SerializedData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getDataFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (dataBuilder_ == null) {
          data_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          dataBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.DataFormats.internal_static_formats_SerializedData_descriptor;
      }

      public proto.DataFormats.SerializedData getDefaultInstanceForType() {
        return proto.DataFormats.SerializedData.getDefaultInstance();
      }

      public proto.DataFormats.SerializedData build() {
        proto.DataFormats.SerializedData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.DataFormats.SerializedData buildPartial() {
        proto.DataFormats.SerializedData result = new proto.DataFormats.SerializedData(this);
        int from_bitField0_ = bitField0_;
        if (dataBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            data_ = java.util.Collections.unmodifiableList(data_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.data_ = data_;
        } else {
          result.data_ = dataBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.DataFormats.SerializedData) {
          return mergeFrom((proto.DataFormats.SerializedData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.DataFormats.SerializedData other) {
        if (other == proto.DataFormats.SerializedData.getDefaultInstance()) return this;
        if (dataBuilder_ == null) {
          if (!other.data_.isEmpty()) {
            if (data_.isEmpty()) {
              data_ = other.data_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureDataIsMutable();
              data_.addAll(other.data_);
            }
            onChanged();
          }
        } else {
          if (!other.data_.isEmpty()) {
            if (dataBuilder_.isEmpty()) {
              dataBuilder_.dispose();
              dataBuilder_ = null;
              data_ = other.data_;
              bitField0_ = (bitField0_ & ~0x00000001);
              dataBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getDataFieldBuilder() : null;
            } else {
              dataBuilder_.addAllMessages(other.data_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.DataFormats.SerializedData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.DataFormats.SerializedData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<proto.DataFormats.Data> data_ =
        java.util.Collections.emptyList();
      private void ensureDataIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          data_ = new java.util.ArrayList<proto.DataFormats.Data>(data_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          proto.DataFormats.Data, proto.DataFormats.Data.Builder, proto.DataFormats.DataOrBuilder> dataBuilder_;

      /**
       * <code>repeated .formats.Data data = 1;</code>
       */
      public java.util.List<proto.DataFormats.Data> getDataList() {
        if (dataBuilder_ == null) {
          return java.util.Collections.unmodifiableList(data_);
        } else {
          return dataBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .formats.Data data = 1;</code>
       */
      public int getDataCount() {
        if (dataBuilder_ == null) {
          return data_.size();
        } else {
          return dataBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .formats.Data data = 1;</code>
       */
      public proto.DataFormats.Data getData(int index) {
        if (dataBuilder_ == null) {
          return data_.get(index);
        } else {
          return dataBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .formats.Data data = 1;</code>
       */
      public Builder setData(
          int index, proto.DataFormats.Data value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.set(index, value);
          onChanged();
        } else {
          dataBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .formats.Data data = 1;</code>
       */
      public Builder setData(
          int index, proto.DataFormats.Data.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.set(index, builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .formats.Data data = 1;</code>
       */
      public Builder addData(proto.DataFormats.Data value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.add(value);
          onChanged();
        } else {
          dataBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .formats.Data data = 1;</code>
       */
      public Builder addData(
          int index, proto.DataFormats.Data value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.add(index, value);
          onChanged();
        } else {
          dataBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .formats.Data data = 1;</code>
       */
      public Builder addData(
          proto.DataFormats.Data.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.add(builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .formats.Data data = 1;</code>
       */
      public Builder addData(
          int index, proto.DataFormats.Data.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.add(index, builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .formats.Data data = 1;</code>
       */
      public Builder addAllData(
          java.lang.Iterable<? extends proto.DataFormats.Data> values) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, data_);
          onChanged();
        } else {
          dataBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .formats.Data data = 1;</code>
       */
      public Builder clearData() {
        if (dataBuilder_ == null) {
          data_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          dataBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .formats.Data data = 1;</code>
       */
      public Builder removeData(int index) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.remove(index);
          onChanged();
        } else {
          dataBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .formats.Data data = 1;</code>
       */
      public proto.DataFormats.Data.Builder getDataBuilder(
          int index) {
        return getDataFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .formats.Data data = 1;</code>
       */
      public proto.DataFormats.DataOrBuilder getDataOrBuilder(
          int index) {
        if (dataBuilder_ == null) {
          return data_.get(index);  } else {
          return dataBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .formats.Data data = 1;</code>
       */
      public java.util.List<? extends proto.DataFormats.DataOrBuilder> 
           getDataOrBuilderList() {
        if (dataBuilder_ != null) {
          return dataBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(data_);
        }
      }
      /**
       * <code>repeated .formats.Data data = 1;</code>
       */
      public proto.DataFormats.Data.Builder addDataBuilder() {
        return getDataFieldBuilder().addBuilder(
            proto.DataFormats.Data.getDefaultInstance());
      }
      /**
       * <code>repeated .formats.Data data = 1;</code>
       */
      public proto.DataFormats.Data.Builder addDataBuilder(
          int index) {
        return getDataFieldBuilder().addBuilder(
            index, proto.DataFormats.Data.getDefaultInstance());
      }
      /**
       * <code>repeated .formats.Data data = 1;</code>
       */
      public java.util.List<proto.DataFormats.Data.Builder> 
           getDataBuilderList() {
        return getDataFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          proto.DataFormats.Data, proto.DataFormats.Data.Builder, proto.DataFormats.DataOrBuilder> 
          getDataFieldBuilder() {
        if (dataBuilder_ == null) {
          dataBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              proto.DataFormats.Data, proto.DataFormats.Data.Builder, proto.DataFormats.DataOrBuilder>(
                  data_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        return dataBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:formats.SerializedData)
    }

    // @@protoc_insertion_point(class_scope:formats.SerializedData)
    private static final proto.DataFormats.SerializedData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.DataFormats.SerializedData();
    }

    public static proto.DataFormats.SerializedData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SerializedData>
        PARSER = new com.google.protobuf.AbstractParser<SerializedData>() {
      public SerializedData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SerializedData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SerializedData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SerializedData> getParserForType() {
      return PARSER;
    }

    public proto.DataFormats.SerializedData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:formats.Data)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.formats.Position pose = 1;</code>
     */
    boolean hasPose();
    /**
     * <code>.formats.Position pose = 1;</code>
     */
    proto.DataFormats.Position getPose();
    /**
     * <code>.formats.Position pose = 1;</code>
     */
    proto.DataFormats.PositionOrBuilder getPoseOrBuilder();

    /**
     * <code>.formats.Heading head = 2;</code>
     */
    boolean hasHead();
    /**
     * <code>.formats.Heading head = 2;</code>
     */
    proto.DataFormats.Heading getHead();
    /**
     * <code>.formats.Heading head = 2;</code>
     */
    proto.DataFormats.HeadingOrBuilder getHeadOrBuilder();
  }
  /**
   * Protobuf type {@code formats.Data}
   */
  public  static final class Data extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:formats.Data)
      DataOrBuilder {
    // Use Data.newBuilder() to construct.
    private Data(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Data() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Data(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              proto.DataFormats.Position.Builder subBuilder = null;
              if (pose_ != null) {
                subBuilder = pose_.toBuilder();
              }
              pose_ = input.readMessage(proto.DataFormats.Position.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(pose_);
                pose_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              proto.DataFormats.Heading.Builder subBuilder = null;
              if (head_ != null) {
                subBuilder = head_.toBuilder();
              }
              head_ = input.readMessage(proto.DataFormats.Heading.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(head_);
                head_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.DataFormats.internal_static_formats_Data_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.DataFormats.internal_static_formats_Data_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.DataFormats.Data.class, proto.DataFormats.Data.Builder.class);
    }

    public static final int POSE_FIELD_NUMBER = 1;
    private proto.DataFormats.Position pose_;
    /**
     * <code>.formats.Position pose = 1;</code>
     */
    public boolean hasPose() {
      return pose_ != null;
    }
    /**
     * <code>.formats.Position pose = 1;</code>
     */
    public proto.DataFormats.Position getPose() {
      return pose_ == null ? proto.DataFormats.Position.getDefaultInstance() : pose_;
    }
    /**
     * <code>.formats.Position pose = 1;</code>
     */
    public proto.DataFormats.PositionOrBuilder getPoseOrBuilder() {
      return getPose();
    }

    public static final int HEAD_FIELD_NUMBER = 2;
    private proto.DataFormats.Heading head_;
    /**
     * <code>.formats.Heading head = 2;</code>
     */
    public boolean hasHead() {
      return head_ != null;
    }
    /**
     * <code>.formats.Heading head = 2;</code>
     */
    public proto.DataFormats.Heading getHead() {
      return head_ == null ? proto.DataFormats.Heading.getDefaultInstance() : head_;
    }
    /**
     * <code>.formats.Heading head = 2;</code>
     */
    public proto.DataFormats.HeadingOrBuilder getHeadOrBuilder() {
      return getHead();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (pose_ != null) {
        output.writeMessage(1, getPose());
      }
      if (head_ != null) {
        output.writeMessage(2, getHead());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (pose_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getPose());
      }
      if (head_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getHead());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.DataFormats.Data)) {
        return super.equals(obj);
      }
      proto.DataFormats.Data other = (proto.DataFormats.Data) obj;

      boolean result = true;
      result = result && (hasPose() == other.hasPose());
      if (hasPose()) {
        result = result && getPose()
            .equals(other.getPose());
      }
      result = result && (hasHead() == other.hasHead());
      if (hasHead()) {
        result = result && getHead()
            .equals(other.getHead());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPose()) {
        hash = (37 * hash) + POSE_FIELD_NUMBER;
        hash = (53 * hash) + getPose().hashCode();
      }
      if (hasHead()) {
        hash = (37 * hash) + HEAD_FIELD_NUMBER;
        hash = (53 * hash) + getHead().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.DataFormats.Data parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.DataFormats.Data parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.DataFormats.Data parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.DataFormats.Data parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.DataFormats.Data parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.DataFormats.Data parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.DataFormats.Data parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.DataFormats.Data parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.DataFormats.Data parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.DataFormats.Data parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.DataFormats.Data prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code formats.Data}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:formats.Data)
        proto.DataFormats.DataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.DataFormats.internal_static_formats_Data_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.DataFormats.internal_static_formats_Data_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.DataFormats.Data.class, proto.DataFormats.Data.Builder.class);
      }

      // Construct using proto.DataFormats.Data.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (poseBuilder_ == null) {
          pose_ = null;
        } else {
          pose_ = null;
          poseBuilder_ = null;
        }
        if (headBuilder_ == null) {
          head_ = null;
        } else {
          head_ = null;
          headBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.DataFormats.internal_static_formats_Data_descriptor;
      }

      public proto.DataFormats.Data getDefaultInstanceForType() {
        return proto.DataFormats.Data.getDefaultInstance();
      }

      public proto.DataFormats.Data build() {
        proto.DataFormats.Data result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.DataFormats.Data buildPartial() {
        proto.DataFormats.Data result = new proto.DataFormats.Data(this);
        if (poseBuilder_ == null) {
          result.pose_ = pose_;
        } else {
          result.pose_ = poseBuilder_.build();
        }
        if (headBuilder_ == null) {
          result.head_ = head_;
        } else {
          result.head_ = headBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.DataFormats.Data) {
          return mergeFrom((proto.DataFormats.Data)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.DataFormats.Data other) {
        if (other == proto.DataFormats.Data.getDefaultInstance()) return this;
        if (other.hasPose()) {
          mergePose(other.getPose());
        }
        if (other.hasHead()) {
          mergeHead(other.getHead());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.DataFormats.Data parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.DataFormats.Data) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private proto.DataFormats.Position pose_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.DataFormats.Position, proto.DataFormats.Position.Builder, proto.DataFormats.PositionOrBuilder> poseBuilder_;
      /**
       * <code>.formats.Position pose = 1;</code>
       */
      public boolean hasPose() {
        return poseBuilder_ != null || pose_ != null;
      }
      /**
       * <code>.formats.Position pose = 1;</code>
       */
      public proto.DataFormats.Position getPose() {
        if (poseBuilder_ == null) {
          return pose_ == null ? proto.DataFormats.Position.getDefaultInstance() : pose_;
        } else {
          return poseBuilder_.getMessage();
        }
      }
      /**
       * <code>.formats.Position pose = 1;</code>
       */
      public Builder setPose(proto.DataFormats.Position value) {
        if (poseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          pose_ = value;
          onChanged();
        } else {
          poseBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.formats.Position pose = 1;</code>
       */
      public Builder setPose(
          proto.DataFormats.Position.Builder builderForValue) {
        if (poseBuilder_ == null) {
          pose_ = builderForValue.build();
          onChanged();
        } else {
          poseBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.formats.Position pose = 1;</code>
       */
      public Builder mergePose(proto.DataFormats.Position value) {
        if (poseBuilder_ == null) {
          if (pose_ != null) {
            pose_ =
              proto.DataFormats.Position.newBuilder(pose_).mergeFrom(value).buildPartial();
          } else {
            pose_ = value;
          }
          onChanged();
        } else {
          poseBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.formats.Position pose = 1;</code>
       */
      public Builder clearPose() {
        if (poseBuilder_ == null) {
          pose_ = null;
          onChanged();
        } else {
          pose_ = null;
          poseBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.formats.Position pose = 1;</code>
       */
      public proto.DataFormats.Position.Builder getPoseBuilder() {
        
        onChanged();
        return getPoseFieldBuilder().getBuilder();
      }
      /**
       * <code>.formats.Position pose = 1;</code>
       */
      public proto.DataFormats.PositionOrBuilder getPoseOrBuilder() {
        if (poseBuilder_ != null) {
          return poseBuilder_.getMessageOrBuilder();
        } else {
          return pose_ == null ?
              proto.DataFormats.Position.getDefaultInstance() : pose_;
        }
      }
      /**
       * <code>.formats.Position pose = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.DataFormats.Position, proto.DataFormats.Position.Builder, proto.DataFormats.PositionOrBuilder> 
          getPoseFieldBuilder() {
        if (poseBuilder_ == null) {
          poseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              proto.DataFormats.Position, proto.DataFormats.Position.Builder, proto.DataFormats.PositionOrBuilder>(
                  getPose(),
                  getParentForChildren(),
                  isClean());
          pose_ = null;
        }
        return poseBuilder_;
      }

      private proto.DataFormats.Heading head_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.DataFormats.Heading, proto.DataFormats.Heading.Builder, proto.DataFormats.HeadingOrBuilder> headBuilder_;
      /**
       * <code>.formats.Heading head = 2;</code>
       */
      public boolean hasHead() {
        return headBuilder_ != null || head_ != null;
      }
      /**
       * <code>.formats.Heading head = 2;</code>
       */
      public proto.DataFormats.Heading getHead() {
        if (headBuilder_ == null) {
          return head_ == null ? proto.DataFormats.Heading.getDefaultInstance() : head_;
        } else {
          return headBuilder_.getMessage();
        }
      }
      /**
       * <code>.formats.Heading head = 2;</code>
       */
      public Builder setHead(proto.DataFormats.Heading value) {
        if (headBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          head_ = value;
          onChanged();
        } else {
          headBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.formats.Heading head = 2;</code>
       */
      public Builder setHead(
          proto.DataFormats.Heading.Builder builderForValue) {
        if (headBuilder_ == null) {
          head_ = builderForValue.build();
          onChanged();
        } else {
          headBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.formats.Heading head = 2;</code>
       */
      public Builder mergeHead(proto.DataFormats.Heading value) {
        if (headBuilder_ == null) {
          if (head_ != null) {
            head_ =
              proto.DataFormats.Heading.newBuilder(head_).mergeFrom(value).buildPartial();
          } else {
            head_ = value;
          }
          onChanged();
        } else {
          headBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.formats.Heading head = 2;</code>
       */
      public Builder clearHead() {
        if (headBuilder_ == null) {
          head_ = null;
          onChanged();
        } else {
          head_ = null;
          headBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.formats.Heading head = 2;</code>
       */
      public proto.DataFormats.Heading.Builder getHeadBuilder() {
        
        onChanged();
        return getHeadFieldBuilder().getBuilder();
      }
      /**
       * <code>.formats.Heading head = 2;</code>
       */
      public proto.DataFormats.HeadingOrBuilder getHeadOrBuilder() {
        if (headBuilder_ != null) {
          return headBuilder_.getMessageOrBuilder();
        } else {
          return head_ == null ?
              proto.DataFormats.Heading.getDefaultInstance() : head_;
        }
      }
      /**
       * <code>.formats.Heading head = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.DataFormats.Heading, proto.DataFormats.Heading.Builder, proto.DataFormats.HeadingOrBuilder> 
          getHeadFieldBuilder() {
        if (headBuilder_ == null) {
          headBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              proto.DataFormats.Heading, proto.DataFormats.Heading.Builder, proto.DataFormats.HeadingOrBuilder>(
                  getHead(),
                  getParentForChildren(),
                  isClean());
          head_ = null;
        }
        return headBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:formats.Data)
    }

    // @@protoc_insertion_point(class_scope:formats.Data)
    private static final proto.DataFormats.Data DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.DataFormats.Data();
    }

    public static proto.DataFormats.Data getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Data>
        PARSER = new com.google.protobuf.AbstractParser<Data>() {
      public Data parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Data(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Data> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Data> getParserForType() {
      return PARSER;
    }

    public proto.DataFormats.Data getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PositionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:formats.Position)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>float lat = 1;</code>
     */
    float getLat();

    /**
     * <code>float long = 2;</code>
     */
    float getLong();

    /**
     * <code>float alt = 3;</code>
     */
    float getAlt();
  }
  /**
   * Protobuf type {@code formats.Position}
   */
  public  static final class Position extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:formats.Position)
      PositionOrBuilder {
    // Use Position.newBuilder() to construct.
    private Position(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Position() {
      lat_ = 0F;
      long_ = 0F;
      alt_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Position(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 13: {

              lat_ = input.readFloat();
              break;
            }
            case 21: {

              long_ = input.readFloat();
              break;
            }
            case 29: {

              alt_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.DataFormats.internal_static_formats_Position_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.DataFormats.internal_static_formats_Position_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.DataFormats.Position.class, proto.DataFormats.Position.Builder.class);
    }

    public static final int LAT_FIELD_NUMBER = 1;
    private float lat_;
    /**
     * <code>float lat = 1;</code>
     */
    public float getLat() {
      return lat_;
    }

    public static final int LONG_FIELD_NUMBER = 2;
    private float long_;
    /**
     * <code>float long = 2;</code>
     */
    public float getLong() {
      return long_;
    }

    public static final int ALT_FIELD_NUMBER = 3;
    private float alt_;
    /**
     * <code>float alt = 3;</code>
     */
    public float getAlt() {
      return alt_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (lat_ != 0F) {
        output.writeFloat(1, lat_);
      }
      if (long_ != 0F) {
        output.writeFloat(2, long_);
      }
      if (alt_ != 0F) {
        output.writeFloat(3, alt_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (lat_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, lat_);
      }
      if (long_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, long_);
      }
      if (alt_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, alt_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.DataFormats.Position)) {
        return super.equals(obj);
      }
      proto.DataFormats.Position other = (proto.DataFormats.Position) obj;

      boolean result = true;
      result = result && (
          java.lang.Float.floatToIntBits(getLat())
          == java.lang.Float.floatToIntBits(
              other.getLat()));
      result = result && (
          java.lang.Float.floatToIntBits(getLong())
          == java.lang.Float.floatToIntBits(
              other.getLong()));
      result = result && (
          java.lang.Float.floatToIntBits(getAlt())
          == java.lang.Float.floatToIntBits(
              other.getAlt()));
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LAT_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getLat());
      hash = (37 * hash) + LONG_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getLong());
      hash = (37 * hash) + ALT_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getAlt());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.DataFormats.Position parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.DataFormats.Position parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.DataFormats.Position parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.DataFormats.Position parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.DataFormats.Position parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.DataFormats.Position parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.DataFormats.Position parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.DataFormats.Position parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.DataFormats.Position parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.DataFormats.Position parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.DataFormats.Position prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code formats.Position}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:formats.Position)
        proto.DataFormats.PositionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.DataFormats.internal_static_formats_Position_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.DataFormats.internal_static_formats_Position_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.DataFormats.Position.class, proto.DataFormats.Position.Builder.class);
      }

      // Construct using proto.DataFormats.Position.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        lat_ = 0F;

        long_ = 0F;

        alt_ = 0F;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.DataFormats.internal_static_formats_Position_descriptor;
      }

      public proto.DataFormats.Position getDefaultInstanceForType() {
        return proto.DataFormats.Position.getDefaultInstance();
      }

      public proto.DataFormats.Position build() {
        proto.DataFormats.Position result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.DataFormats.Position buildPartial() {
        proto.DataFormats.Position result = new proto.DataFormats.Position(this);
        result.lat_ = lat_;
        result.long_ = long_;
        result.alt_ = alt_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.DataFormats.Position) {
          return mergeFrom((proto.DataFormats.Position)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.DataFormats.Position other) {
        if (other == proto.DataFormats.Position.getDefaultInstance()) return this;
        if (other.getLat() != 0F) {
          setLat(other.getLat());
        }
        if (other.getLong() != 0F) {
          setLong(other.getLong());
        }
        if (other.getAlt() != 0F) {
          setAlt(other.getAlt());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.DataFormats.Position parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.DataFormats.Position) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private float lat_ ;
      /**
       * <code>float lat = 1;</code>
       */
      public float getLat() {
        return lat_;
      }
      /**
       * <code>float lat = 1;</code>
       */
      public Builder setLat(float value) {
        
        lat_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float lat = 1;</code>
       */
      public Builder clearLat() {
        
        lat_ = 0F;
        onChanged();
        return this;
      }

      private float long_ ;
      /**
       * <code>float long = 2;</code>
       */
      public float getLong() {
        return long_;
      }
      /**
       * <code>float long = 2;</code>
       */
      public Builder setLong(float value) {
        
        long_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float long = 2;</code>
       */
      public Builder clearLong() {
        
        long_ = 0F;
        onChanged();
        return this;
      }

      private float alt_ ;
      /**
       * <code>float alt = 3;</code>
       */
      public float getAlt() {
        return alt_;
      }
      /**
       * <code>float alt = 3;</code>
       */
      public Builder setAlt(float value) {
        
        alt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float alt = 3;</code>
       */
      public Builder clearAlt() {
        
        alt_ = 0F;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:formats.Position)
    }

    // @@protoc_insertion_point(class_scope:formats.Position)
    private static final proto.DataFormats.Position DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.DataFormats.Position();
    }

    public static proto.DataFormats.Position getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Position>
        PARSER = new com.google.protobuf.AbstractParser<Position>() {
      public Position parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Position(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Position> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Position> getParserForType() {
      return PARSER;
    }

    public proto.DataFormats.Position getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HeadingOrBuilder extends
      // @@protoc_insertion_point(interface_extends:formats.Heading)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>float roll_deg = 1;</code>
     */
    float getRollDeg();

    /**
     * <code>float pitch_deg = 2;</code>
     */
    float getPitchDeg();

    /**
     * <code>float yaw_deg = 3;</code>
     */
    float getYawDeg();
  }
  /**
   * Protobuf type {@code formats.Heading}
   */
  public  static final class Heading extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:formats.Heading)
      HeadingOrBuilder {
    // Use Heading.newBuilder() to construct.
    private Heading(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Heading() {
      rollDeg_ = 0F;
      pitchDeg_ = 0F;
      yawDeg_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Heading(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 13: {

              rollDeg_ = input.readFloat();
              break;
            }
            case 21: {

              pitchDeg_ = input.readFloat();
              break;
            }
            case 29: {

              yawDeg_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.DataFormats.internal_static_formats_Heading_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.DataFormats.internal_static_formats_Heading_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.DataFormats.Heading.class, proto.DataFormats.Heading.Builder.class);
    }

    public static final int ROLL_DEG_FIELD_NUMBER = 1;
    private float rollDeg_;
    /**
     * <code>float roll_deg = 1;</code>
     */
    public float getRollDeg() {
      return rollDeg_;
    }

    public static final int PITCH_DEG_FIELD_NUMBER = 2;
    private float pitchDeg_;
    /**
     * <code>float pitch_deg = 2;</code>
     */
    public float getPitchDeg() {
      return pitchDeg_;
    }

    public static final int YAW_DEG_FIELD_NUMBER = 3;
    private float yawDeg_;
    /**
     * <code>float yaw_deg = 3;</code>
     */
    public float getYawDeg() {
      return yawDeg_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (rollDeg_ != 0F) {
        output.writeFloat(1, rollDeg_);
      }
      if (pitchDeg_ != 0F) {
        output.writeFloat(2, pitchDeg_);
      }
      if (yawDeg_ != 0F) {
        output.writeFloat(3, yawDeg_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (rollDeg_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, rollDeg_);
      }
      if (pitchDeg_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, pitchDeg_);
      }
      if (yawDeg_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, yawDeg_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.DataFormats.Heading)) {
        return super.equals(obj);
      }
      proto.DataFormats.Heading other = (proto.DataFormats.Heading) obj;

      boolean result = true;
      result = result && (
          java.lang.Float.floatToIntBits(getRollDeg())
          == java.lang.Float.floatToIntBits(
              other.getRollDeg()));
      result = result && (
          java.lang.Float.floatToIntBits(getPitchDeg())
          == java.lang.Float.floatToIntBits(
              other.getPitchDeg()));
      result = result && (
          java.lang.Float.floatToIntBits(getYawDeg())
          == java.lang.Float.floatToIntBits(
              other.getYawDeg()));
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ROLL_DEG_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getRollDeg());
      hash = (37 * hash) + PITCH_DEG_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getPitchDeg());
      hash = (37 * hash) + YAW_DEG_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getYawDeg());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.DataFormats.Heading parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.DataFormats.Heading parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.DataFormats.Heading parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.DataFormats.Heading parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.DataFormats.Heading parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.DataFormats.Heading parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.DataFormats.Heading parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.DataFormats.Heading parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.DataFormats.Heading parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.DataFormats.Heading parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.DataFormats.Heading prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code formats.Heading}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:formats.Heading)
        proto.DataFormats.HeadingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.DataFormats.internal_static_formats_Heading_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.DataFormats.internal_static_formats_Heading_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.DataFormats.Heading.class, proto.DataFormats.Heading.Builder.class);
      }

      // Construct using proto.DataFormats.Heading.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        rollDeg_ = 0F;

        pitchDeg_ = 0F;

        yawDeg_ = 0F;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.DataFormats.internal_static_formats_Heading_descriptor;
      }

      public proto.DataFormats.Heading getDefaultInstanceForType() {
        return proto.DataFormats.Heading.getDefaultInstance();
      }

      public proto.DataFormats.Heading build() {
        proto.DataFormats.Heading result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.DataFormats.Heading buildPartial() {
        proto.DataFormats.Heading result = new proto.DataFormats.Heading(this);
        result.rollDeg_ = rollDeg_;
        result.pitchDeg_ = pitchDeg_;
        result.yawDeg_ = yawDeg_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.DataFormats.Heading) {
          return mergeFrom((proto.DataFormats.Heading)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.DataFormats.Heading other) {
        if (other == proto.DataFormats.Heading.getDefaultInstance()) return this;
        if (other.getRollDeg() != 0F) {
          setRollDeg(other.getRollDeg());
        }
        if (other.getPitchDeg() != 0F) {
          setPitchDeg(other.getPitchDeg());
        }
        if (other.getYawDeg() != 0F) {
          setYawDeg(other.getYawDeg());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.DataFormats.Heading parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.DataFormats.Heading) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private float rollDeg_ ;
      /**
       * <code>float roll_deg = 1;</code>
       */
      public float getRollDeg() {
        return rollDeg_;
      }
      /**
       * <code>float roll_deg = 1;</code>
       */
      public Builder setRollDeg(float value) {
        
        rollDeg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float roll_deg = 1;</code>
       */
      public Builder clearRollDeg() {
        
        rollDeg_ = 0F;
        onChanged();
        return this;
      }

      private float pitchDeg_ ;
      /**
       * <code>float pitch_deg = 2;</code>
       */
      public float getPitchDeg() {
        return pitchDeg_;
      }
      /**
       * <code>float pitch_deg = 2;</code>
       */
      public Builder setPitchDeg(float value) {
        
        pitchDeg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float pitch_deg = 2;</code>
       */
      public Builder clearPitchDeg() {
        
        pitchDeg_ = 0F;
        onChanged();
        return this;
      }

      private float yawDeg_ ;
      /**
       * <code>float yaw_deg = 3;</code>
       */
      public float getYawDeg() {
        return yawDeg_;
      }
      /**
       * <code>float yaw_deg = 3;</code>
       */
      public Builder setYawDeg(float value) {
        
        yawDeg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float yaw_deg = 3;</code>
       */
      public Builder clearYawDeg() {
        
        yawDeg_ = 0F;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:formats.Heading)
    }

    // @@protoc_insertion_point(class_scope:formats.Heading)
    private static final proto.DataFormats.Heading DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.DataFormats.Heading();
    }

    public static proto.DataFormats.Heading getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Heading>
        PARSER = new com.google.protobuf.AbstractParser<Heading>() {
      public Heading parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Heading(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Heading> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Heading> getParserForType() {
      return PARSER;
    }

    public proto.DataFormats.Heading getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_formats_SerializedData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_formats_SerializedData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_formats_Data_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_formats_Data_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_formats_Position_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_formats_Position_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_formats_Heading_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_formats_Heading_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\robjects.proto\022\007formats\"-\n\016SerializedDa" +
      "ta\022\033\n\004data\030\001 \003(\0132\r.formats.Data\"G\n\004Data\022" +
      "\037\n\004pose\030\001 \001(\0132\021.formats.Position\022\036\n\004head" +
      "\030\002 \001(\0132\020.formats.Heading\"2\n\010Position\022\013\n\003" +
      "lat\030\001 \001(\002\022\014\n\004long\030\002 \001(\002\022\013\n\003alt\030\003 \001(\002\"?\n\007" +
      "Heading\022\020\n\010roll_deg\030\001 \001(\002\022\021\n\tpitch_deg\030\002" +
      " \001(\002\022\017\n\007yaw_deg\030\003 \001(\002B\024\n\005protoB\013DataForm" +
      "atsb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_formats_SerializedData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_formats_SerializedData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_formats_SerializedData_descriptor,
        new java.lang.String[] { "Data", });
    internal_static_formats_Data_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_formats_Data_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_formats_Data_descriptor,
        new java.lang.String[] { "Pose", "Head", });
    internal_static_formats_Position_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_formats_Position_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_formats_Position_descriptor,
        new java.lang.String[] { "Lat", "Long", "Alt", });
    internal_static_formats_Heading_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_formats_Heading_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_formats_Heading_descriptor,
        new java.lang.String[] { "RollDeg", "PitchDeg", "YawDeg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
